#!/usr/bin/env bash
set -euo pipefail

IPA_PATH="${1:-}"
BUNDLE_ID="${2:-solumate.driver.automation}"
XCTESTCONFIG="${3:-WebDriverAgentRunner.xctest}"
UDID="${GO_IOS_UDID:-${UDID:-}}"
WDA_PORT="${WDA_PORT:-8000}"
MJPEG_PORT="${MJPEG_PORT:-8001}"
H264_PORT="${H264_PORT:-8002}"
REALTIME_CONTROL_PORT="${REALTIME_CONTROL_PORT:-8003}"
MJPEG_SCALING_FACTOR="${MJPEG_SCALING_FACTOR:-45}"
MJPEG_SERVER_SCREENSHOT_QUALITY="${MJPEG_SERVER_SCREENSHOT_QUALITY:-20}"
MJPEG_SERVER_FRAMERATE="${MJPEG_SERVER_FRAMERATE:-30}"
MJPEG_FIX_ORIENTATION="${MJPEG_FIX_ORIENTATION:-true}"
MJPEG_FRAME_TIMEOUT="${MJPEG_FRAME_TIMEOUT:-0.45}"
H264_MAX_WIDTH="${H264_MAX_WIDTH:-960}"
H264_MAX_HEIGHT="${H264_MAX_HEIGHT:-960}"
H264_BITRATE="${H264_BITRATE:-1800000}"
H264_FPS="${H264_FPS:-15}"
H264_GOP="${H264_GOP:-3}"
H264_QUALITY="${H264_QUALITY:-30}"
WDA_STARTUP_PASSWORD="${WDA_STARTUP_PASSWORD:-}"
WDA_AUTH_TOKEN="${WDA_AUTH_TOKEN:-${WEBDRIVERAGENT_AUTH_TOKEN:-}}"
SOLUMATE_WDA_ENABLE_POINT_ARRAY="${SOLUMATE_WDA_ENABLE_POINT_ARRAY:-}"
SOLUMATE_WDA_SWIPE_SECRET="${SOLUMATE_WDA_SWIPE_SECRET:-}"
SOLUMATE_WDA_ALLOW_UNSIGNED_POINT_ARRAY="${SOLUMATE_WDA_ALLOW_UNSIGNED_POINT_ARRAY:-}"

if [[ -z "$IPA_PATH" ]]; then
  echo "Usage: $0 /path/to/WebDriverAgentRunner-Runner.ipa [bundle-id] [xctestconfig]" >&2
  echo "Optional env: GO_IOS_UDID, WDA_PORT, MJPEG_PORT, H264_PORT, REALTIME_CONTROL_PORT, MJPEG_SCALING_FACTOR, MJPEG_SERVER_SCREENSHOT_QUALITY, MJPEG_SERVER_FRAMERATE, MJPEG_FIX_ORIENTATION, MJPEG_FRAME_TIMEOUT, H264_MAX_WIDTH, H264_MAX_HEIGHT, H264_BITRATE, H264_FPS, H264_GOP, H264_QUALITY, WDA_STARTUP_PASSWORD, WDA_AUTH_TOKEN, SOLUMATE_WDA_ENABLE_POINT_ARRAY, SOLUMATE_WDA_SWIPE_SECRET, SOLUMATE_WDA_ALLOW_UNSIGNED_POINT_ARRAY" >&2
  exit 1
fi

echo "Installing IPA: $IPA_PATH"
if [[ -n "$UDID" ]]; then
  ios --udid="$UDID" install --path="$IPA_PATH"
else
  ios install --path="$IPA_PATH"
fi

if [[ -z "$WDA_STARTUP_PASSWORD" ]]; then
  echo "Warning: WDA_STARTUP_PASSWORD is empty. If your WDA build requires startup password, runwda will abort." >&2
fi
if [[ -n "$SOLUMATE_WDA_ENABLE_POINT_ARRAY" && -z "$SOLUMATE_WDA_SWIPE_SECRET" && -z "$SOLUMATE_WDA_ALLOW_UNSIGNED_POINT_ARRAY" ]]; then
  echo "Warning: SOLUMATE_WDA_ENABLE_POINT_ARRAY is set but SOLUMATE_WDA_SWIPE_SECRET is empty. Secure builds reject unsigned pointArray requests." >&2
fi

echo "Starting WDA with bundle id: $BUNDLE_ID (WDA:$WDA_PORT MJPEG:$MJPEG_PORT H264:$H264_PORT CTRL:$REALTIME_CONTROL_PORT scale:$MJPEG_SCALING_FACTOR quality:$MJPEG_SERVER_SCREENSHOT_QUALITY fps:$MJPEG_SERVER_FRAMERATE)"

IOS_CMD=(ios)
if [[ -n "$UDID" ]]; then
  IOS_CMD+=(--udid="$UDID")
fi
IOS_CMD+=(
  runwda
  --bundleid="$BUNDLE_ID"
  --testrunnerbundleid="$BUNDLE_ID"
  --xctestconfig="$XCTESTCONFIG"
  --env=USE_PORT="$WDA_PORT"
  --env=MJPEG_SERVER_PORT="$MJPEG_PORT"
  --env=H264_SERVER_PORT="$H264_PORT"
  --env=WDA_REALTIME_CONTROL_ENABLED=1
  --env=WDA_REALTIME_CONTROL_PORT="$REALTIME_CONTROL_PORT"
  --env=MJPEG_SCALING_FACTOR="$MJPEG_SCALING_FACTOR"
  --env=MJPEG_SERVER_SCREENSHOT_QUALITY="$MJPEG_SERVER_SCREENSHOT_QUALITY"
  --env=MJPEG_SERVER_FRAMERATE="$MJPEG_SERVER_FRAMERATE"
  --env=MJPEG_FIX_ORIENTATION="$MJPEG_FIX_ORIENTATION"
  --env=MJPEG_FRAME_TIMEOUT="$MJPEG_FRAME_TIMEOUT"
  --env=H264_MAX_WIDTH="$H264_MAX_WIDTH"
  --env=H264_MAX_HEIGHT="$H264_MAX_HEIGHT"
  --env=H264_BITRATE="$H264_BITRATE"
  --env=H264_FPS="$H264_FPS"
  --env=H264_GOP="$H264_GOP"
  --env=H264_QUALITY="$H264_QUALITY"
  --log-output=-
)
if [[ -n "$WDA_STARTUP_PASSWORD" ]]; then
  IOS_CMD+=(--env=WDA_STARTUP_PASSWORD="$WDA_STARTUP_PASSWORD")
fi
if [[ -n "$WDA_AUTH_TOKEN" ]]; then
  IOS_CMD+=(--env=WDA_AUTH_TOKEN="$WDA_AUTH_TOKEN")
fi
if [[ -n "$SOLUMATE_WDA_ENABLE_POINT_ARRAY" ]]; then
  IOS_CMD+=(--env=SOLUMATE_WDA_ENABLE_POINT_ARRAY="$SOLUMATE_WDA_ENABLE_POINT_ARRAY")
fi
if [[ -n "$SOLUMATE_WDA_SWIPE_SECRET" ]]; then
  IOS_CMD+=(--env=SOLUMATE_WDA_SWIPE_SECRET="$SOLUMATE_WDA_SWIPE_SECRET")
fi
if [[ -n "$SOLUMATE_WDA_ALLOW_UNSIGNED_POINT_ARRAY" ]]; then
  IOS_CMD+=(--env=SOLUMATE_WDA_ALLOW_UNSIGNED_POINT_ARRAY="$SOLUMATE_WDA_ALLOW_UNSIGNED_POINT_ARRAY")
fi

"${IOS_CMD[@]}"
